---
#adapted from edx configuration
- name: Copy mongodb key file from master to mongodb_repl
  command: scp "{{ mongo_key_file }}" root@"{{ groups['mongodb_repl'][0] }}":"{{ mongo_key_file }}"
  delegate_to: "{{ groups['localhost'][0] }}"

- name: Configure security for key file
  file:
    dest: "{{ mongo_key_file }}"
    mode: "0600"
    owner: mongodb
    group: mongodb
  delegate_to: "{{ groups['mongodb_repl'][0] }}"

- name: Configure mongodb.conf for SECONDARY
  include: mongodb_conf.yml
  delegate_to: "{{ groups['mongodb_repl'][0] }}"



