---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: datastores
  sudo: True
  gather_facts: True
  vars:
    MYSQL_BIND_ADDRESS: "0.0.0.0"
    EDXLOCAL_MYSQL_ALLOWED_HOST: "{{ hostvars['stateless'][0]['ansible_hostname'] }}"
    STATELESS_HOST: "{{ groups['stateless'][0] }}"
#    EDXLOCAL_MYSQL_ALLOWED_HOST: "203.252.119.102"
#    rabbitmq_ip: "{{ groups['datastores'][0] }}"
  vars_files:
    - "/var/tmp/configuration/playbooks/roles/edxapp/defaults/main.yml"
    - "/var/tmp/configuration/playbooks/roles/forum/defaults/main.yml"
    - "/var/tmp/configuration/playbooks/roles/xqueue/defaults/main.yml"
    - "/var/tmp/configuration/playbooks/roles/ecommerce/defaults/main.yml"
    - "/var/tmp/configuration/playbooks/roles/ecomworker/defaults/main.yml"
  roles:
    # This install mysql and creates users.
    - role: memcache
    - role: mongo_3_2
    - role: rabbitmq
    - role: oraclejdk
    - role: elasticsearch
    - role: edxlocal
    - role: edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC

  tasks:
    - include: create_mysql_users.yml
    - include: address_binding.yml
