---
- hosts: datastores
  tasks:
    - name: Configure mySQL replication
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^#server-id', line: 'server-id = 1' }
        - { regexp: '^#log_bin', line: '/var/log/mysql/mysql-bin.log' }
        - { regexp: '^max_allowed_packet', line: 'max_allowed_packet      = 1G' }
      blockinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        block: |
          binlog_do_db            = ecommerce
          binlog_do_db            = edxapp
          binlog_do_db            = edxapp_csmh
          binlog_do_db            = xqueue
    - service: mysql
      state: restarted

- hosts: mysql_slave
  become: true
  tasks:
    - name: install mySQL
      apt: name={{item}} state=present
      with_items:
        - mysql-server
        - mysql-client
    - name: Set MySQL bind-address
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
