---
- name: Configure mySQL replication
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#server-id', line: 'server-id = 1' }
    - { regexp: '^#log_bin', line: '/var/log/mysql/mysql-bin.log' }
    - { regexp: '^max_allowed_packet', line: 'max_allowed_packet      = 1G' }
- name: Add binlog info
  blockinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    block: |
      binlog_do_db            = ecommerce
      binlog_do_db            = edxapp
      binlog_do_db            = edxapp_csmh
      binlog_do_db            = xqueue
- name: Restart mySQL
  service:
    name: mysql
    state: restarted

