---
#set up slave server
- name: Install mySQL on Slave
  apt: name={{item}} state=present
  with_items:
    - mysql-server
    - mysql-client
- name: Set MySQL configuration for Slave
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "{{ item.regexp }}"
  with_items:
    - { regexp: '^server-id', line: 'server-id = 2' }
    - { regexp: '^log_bin', line: 'log_bin = /var/log/mysql/mysql-bin.log' }
    - { regexp: '^max_allowed_packet', line: 'max_allowed_packet      = 1G' }line: "{{ item.line }}"

#set up master server
- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
   - "{{ groups['datastores'][0] }}"
   - "{{ groups['mysql_slave'][0] }}"

- name: Configure mySQL configuration for Master
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^server-id', line: 'server-id = 1' }
    - { regexp: '^log_bin', line: 'log_bin = /var/log/mysql/mysql-bin.log' }
    - { regexp: '^max_allowed_packet', line: 'max_allowed_packet      = 1G' }

- name: Add binlog info
  blockinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    block: |
      binlog_do_db            = ecommerce
      binlog_do_db            = edxapp
      binlog_do_db            = edxapp_csmh
      binlog_do_db            = xqueue

- name: Restart mySQL
  service:
    name: mysql
    state: restarted

- name: Create mySQL Slave User
  mysql_user: 
    name: "{{ MYSQL_SLAVE_USER }}"
    host: "%"
    password: "{{ MYSQL_SLAVE_PASSWORD }}"
    priv: "*.*:REPLICATION SLAVE"

- name: Get Master Status
  mysql_replication: mode=getmaster
  register: master_status

- name: 
