- name: install mySQL
  apt: name={{item}} state=present
  with_items:
    - mysql-server
    - mysql-client
- name: Set MySQL bind-address
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'

