---
- name: Setup
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Setup SSH settings
      template:
        src: "templates/sshd_conf.j2"
        dest: "/etc/ssh/sshd_config"

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
   

