---
- name: Setup
  hosts: localhost
  connection: local
  become: true
  vars:
    - UBUNTU_ROOT_PASSWORD: edx

  tasks:
    - name: Password rollover
      user: name=root password="{{ UBUNTU_ROOT_PASSWORD }}"

    - name: Setup SSH settings
      template:
        src: "templates/sshd_conf.j2"
        dest: "/etc/ssh/sshd_config"

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
   

